---
http_interactions:
- request:
    method: get
    uri: https://us.api.battle.net/wow/recipe/33994?apikey=uc5zg6857kv8mfcvnvhxyhxqm6ug8wyx&locale=en_us
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Language:
      - en-US
      Content-Type:
      - application/json;charset=UTF-8
      Date:
      - Sun, 27 Sep 2015 11:18:17 GMT
      Server:
      - Apache
      Vary:
      - Accept-Encoding
      X-Frame-Options:
      - SAMEORIGIN
      X-Mashery-Responder:
      - prod-j-worker-us-east-1b-76.mashery.com
      X-Plan-Qps-Allotted:
      - '100'
      X-Plan-Qps-Current:
      - '1'
      X-Plan-Quota-Allotted:
      - '36000'
      X-Plan-Quota-Current:
      - '79'
      X-Plan-Quota-Reset:
      - Sunday, September 27, 2015 12:00:00 PM GMT
      Content-Length:
      - '105'
      Connection:
      - keep-alive
    body:
      encoding: UTF-8
      string: '{"id":33994,"name":"Precise Strikes","profession":"Enchanting","icon":"spell_holy_greaterheal"}'
    http_version: 
  recorded_at: Sun, 27 Sep 2015 11:18:18 GMT
recorded_with: VCR 2.9.3
